name : Exemple
on:
  push:
    branches:
      - main
jobs:
    update_wakatime_stats:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Wakatime stats
        uses: tot0p/wakatime-readme@v1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}


